=== delez/ssh_scaffold/appeon.aje.web.engine/src/appeon/aje/webengine/meta/meta.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="models">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="model" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="model">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="description" minOccurs="0"/>
				<xs:element ref="Fields"/>
				<xs:element ref="ref"/>
			</xs:sequence>
			<xs:attribute name="name" use="required"/>
			<xs:attribute name="type" use="optional"/>
			<xs:attribute name="tableName" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="description" type="xs:string"/>
	<xs:element name="ref" type="xs:string"/>
	<xs:element name="Fields">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="field" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="field">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="precision"/>
				<xs:element ref="scale"/>
				<xs:element ref="key"/>
				<xs:element ref="identity"/>
				<xs:element ref="isnull"/>
				<xs:element ref="password"/>
				<xs:element ref="initial"/>
				<xs:element ref="values"/>
				<xs:element ref="title"/>
				<xs:element ref="caption"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="type" type="xs:integer" use="required"/>
			<xs:attribute name="len" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="identity" type="xs:boolean"/>
	<xs:element name="initial" type="xs:string"/>
	<xs:element name="isnull" type="xs:boolean"/>
	<xs:element name="key" type="xs:boolean"/>
	<xs:element name="password" type="xs:boolean"/>
	<xs:element name="precision" type="xs:integer"/>
	<xs:element name="scale" type="xs:integer"/>
	<xs:element name="title" type="xs:string"/>
	<xs:element name="caption" type="xs:string"/>
	<xs:element name="values" type="xs:string"/>
</xs:schema>

=== delez/ssh_scaffold/appeon.aje.web.engine/src_test/appeon/aje/webengine/test/xjxl/Point.xml
<models xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="meta.xsd">
	<model name="Point" dbName="T_bszl">
		<description>标石资料（用户登录时是自己的录入的或自己维护范围可以查看）</description>
		<fields>
			<field name="id" dbName="bsbh" type="1" len="10">
				<title>标石编号</title>
				<caption>标石编号</caption>
				<precision>0</precision>
				<scale>0</scale>
				<key>false</key>
				<identity>false</identity>
				<isnull>false</isnull>
				<password>false</password>
				<initial/>
				<values/>
			</field>
			<field name="serialNumber" dbName="nkxh" type="1" len="12">
				<title>钮扣序号</title>
				<caption>钮扣序号</caption>
				<precision>0</precision>
				<scale>0</scale>
				<key>false</key>
				<identity>false</identity>
				<isnull>false</isnull>
				<password>false</password>
				<initial/>
				<values/>
			</field>
			<field name="address" dbName="msdz" type="1" len="60">
				<title>埋设地址</title>
				<caption>埋设地址</caption>
				<precision>0</precision>
				<scale>0</scale>
				<key>false</key>
				<identity>false</identity>
				<isnull>true</isnull>
				<password>false</password>
				<initial/>
				<values/>
			</field>
			<field name="longitude " dbName="jd" type="1" len="9">
				<title>经度</title>
				<caption>经度</caption>
				<precision>0</precision>
				<scale>0</scale>
				<key>false</key>
				<identity>false</identity>
				<isnull>true</isnull>
				<password>false</password>
				<initial/>
				<values/>
			</field>
			<field name="latitude " dbName="wd" type="1" len="9">
				<title>纬度</title>
				<caption>纬度</caption>
				<precision>0</precision>
				<scale>0</scale>
				<key>false</key>
				<identity>false</identity>
				<isnull>true</isnull>
				<password>false</password>
				<initial/>
				<values/>
			</field>
			<field name="pictureId" dbName="tpbh" type="4" len="11">
				<title>图片编码</title>
				<caption>图片编码</caption>
				<precision>0</precision>
				<scale>0</scale>
				<key>false</key>
				<identity>false</identity>
				<isnull>true</isnull>
				<password>false</password>
				<initial/>
				<values/>
			</field>
			<field name="code" dbName="zhbh" type="1" len="23">
				<title>组合编码</title>
				<caption>组合编码</caption>
				<precision>0</precision>
				<scale>0</scale>
				<key>true</key>
				<identity>false</identity>
				<isnull>false</isnull>
				<password>false</password>
				<initial/>
				<values/>
			</field>
			<field name="sectionCode" dbName="dlbh" type="1" len="13">
				<title>段落编码</title>
				<caption>段落编码</caption>
				<precision>0</precision>
				<scale>0</scale>
				<key>false</key>
				<identity>false</identity>
				<isnull>false</isnull>
				<password>false</password>
				<initial/>
				<values/>
			</field>
			<field name="operator" dbName="lry" type="1" len="24">
				<title>维护人员</title>
				<caption>维护人员</caption>
				<precision>0</precision>
				<scale>0</scale>
				<key>false</key>
				<identity>false</identity>
				<isnull>true</isnull>
				<password>false</password>
				<initial/>
				<values/>
			</field>
			<field name="datetime" dbName="xgsj" type="93" len="19">
				<title>修改时间</title>
				<caption>修改时间</caption>
				<precision>0</precision>
				<scale>0</scale>
				<key>false</key>
				<identity>false</identity>
				<isnull>true</isnull>
				<password>false</password>
				<initial/>
				<values/>
			</field>
		</fields>
		<ref/>
	</model>
</models>

=== delez/ssh_scaffold/appeon.aje.web.engine/src_test/appeon/aje/webengine/test/xjxl/Paragraph.xml
<models xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="meta.xsd">
	<model name="Section" dbName="T_dlzl">
		<description>段落资料</description>
		<fields>
			<field name="code" dbName="zhbh" type="1" len="13">
				<title>组合编号（前补3个0＋线路ID）</title>
				<caption>组合编号</caption>
				<precision>0</precision>
				<scale>0</scale>
				<key>true</key>
				<identity>false</identity>
				<isnull>false</isnull>
				<password>false</password>
				<initial/>
				<values/>
			</field>
			<field name="id" dbName="dlbh" type="1" len="3">
				<title>段落编号</title>
				<caption>段落编号</caption>
				<precision>0</precision>
				<scale>0</scale>
				<key>false</key>
				<identity>false</identity>
				<isnull>false</isnull>
				<password>false</password>
				<initial/>
				<values/>
			</field>
			<field name="lineCode" dbName="xlid" type="1" len="10">
				<title>线路（外键）</title>
				<caption>线路</caption>
				<precision>0</precision>
				<scale>0</scale>
				<key>false</key>
				<identity>false</identity>
				<isnull>false</isnull>
				<password>false</password>
				<initial/>
				<values/>
			</field>
			<field name="name" dbName="dlmc" type="1" len="40">
				<title>段落名称</title>
				<caption>段落名称</caption>
				<precision>0</precision>
				<scale>0</scale>
				<key>false</key>
				<identity>false</identity>
				<isnull>false</isnull>
				<password>false</password>
				<initial/>
				<values/>
			</field>
			<field name="start" dbName="dlqd" type="1" len="20">
				<title>段落起点</title>
				<caption>段落起点</caption>
				<precision>0</precision>
				<scale>0</scale>
				<key>false</key>
				<identity>false</identity>
				<isnull>false</isnull>
				<password>false</password>
				<initial/>
				<values/>
			</field>
			<field name="end" dbName="dlzd" type="1" len="20">
				<title>段落终点</title>
				<caption>段落终点</caption>
				<precision>0</precision>
				<scale>0</scale>
				<key>false</key>
				<identity>false</identity>
				<isnull>false</isnull>
				<password>false</password>
				<initial/>
				<values/>
			</field>
			<field name="lenght" dbName="dlcd" type="3" len="18">
				<title>段落长度</title>
				<caption>段落长度</caption>
				<precision>0</precision>
				<scale>0</scale>
				<key>false</key>
				<identity>false</identity>
				<isnull>true</isnull>
				<password>false</password>
				<initial/>
				<values/>
			</field>
			<field name="program" dbName="xlcs" type="1" len="10">
				<title>线路程式（录入）</title>
				<caption>线路程式</caption>
				<precision>0</precision>
				<scale>0</scale>
				<key>false</key>
				<identity>false</identity>
				<isnull>true</isnull>
				<password>false</password>
				<initial/>
				<values/>
			</field>
			<field name="level" dbName="xjjb" type="1" len="4">
				<title>巡检级别（1到4级）</title>
				<caption>巡检级别</caption>
				<precision>0</precision>
				<scale>0</scale>
				<key>false</key>
				<identity>false</identity>
				<isnull>false</isnull>
				<password>false</password>
				<initial/>
				<values/>
			</field>
			<field name="operator" dbName="lry" type="1" len="24">
				<title>维护人员/单位编码</title>
				<caption>护人员/单位编码</caption>
				<precision>0</precision>
				<scale>0</scale>
				<key>false</key>
				<identity>false</identity>
				<isnull>true</isnull>
				<password>false</password>
				<initial/>
				<values/>
			</field>
			<field name="datetime" dbName="xgsj" type="93" len="19">
				<title>修改时间</title>
				<caption>修改时间</caption>
				<precision>0</precision>
				<scale>0</scale>
				<key>false</key>
				<identity>false</identity>
				<isnull>true</isnull>
				<password>false</password>
				<initial/>
				<values/>
			</field>
		</fields>
		<ref/>
	</model>
</models>

=== delez/ssh_scaffold/appeon.aje.web.engine/src_test/appeon/aje/webengine/test/xjxl/PlanDetail.xml
<models xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="meta.xsd">
<model name="PlanDetail" dbName="t_jhbs">
	<description>计划明细</description>
	<fields>
		<field name="id" dbName="zjhbh" type="4" len="11">
			<title>主计划编码</title>
			<caption>主计划编码</caption>
			<precision>0</precision>
			<scale>0</scale>
			<key>false</key>
			<identity>false</identity>
			<isnull>false</isnull>
			<password>false</password>
			<initial/>
			<values/>
		</field>
		<field name="planId" dbName="jhbh" type="4" len="11">
			<title>计划编码</title>
			<caption>计划编码</caption>
			<precision>0</precision>
			<scale>0</scale>
			<key>false</key>
			<identity>false</identity>
			<isnull>false</isnull>
			<password>false</password>
			<initial/>
			<values/>
		</field>
		<field name="code" dbName="zhbh" type="1" len="23">
			<title>组合编码</title>
			<caption>组合编码</caption>
			<precision>0</precision>
			<scale>0</scale>
			<key>false</key>
			<identity>false</identity>
			<isnull>false</isnull>
			<password>false</password>
			<initial/>
			<values/>
		</field>
		<field name="importDate" dbName="dqrq" type="93" len="19">
			<title>读取时间</title>
			<caption>读取时间</caption>
			<precision>0</precision>
			<scale>0</scale>
			<key>false</key>
			<identity>false</identity>
			<isnull>true</isnull>
			<password>false</password>
			<initial/>
			<values/>
		</field>
		<field name="state" dbName="zt" type="1" len="4">
			<title>状态</title>
			<caption>状态</caption>
			<precision>0</precision>
			<scale>0</scale>
			<key>false</key>
			<identity>false</identity>
			<isnull>false</isnull>
			<password>false</password>
			<initial/>
			<values/>
		</field>
		<field name="datetime" dbName="xgsj" type="93" len="19">
			<title>修改时间</title>
			<caption>修改时间</caption>
			<precision>0</precision>
			<scale>0</scale>
			<key>false</key>
			<identity>false</identity>
			<isnull>false</isnull>
			<password>false</password>
			<initial/>
			<values/>
		</field>
	</fields>
	<ref/>
</model>
</models>
